Algoritmo "estruturaDeRepeticao"
// Disciplina : [Linguagem e Lógica de Programação]
// Professor : Jailson Costa dos Santos
// Descrição : Estrutura de Repetição Enquanto
// Autor(a) : Leonardo Mendes
// Data atual : 30/03/2022
Var
// Seção de Declarações das variáveis
contadora:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
    enquanto contadora<10 faca
        Escreval("Leonardo")
        contadora<-contadora+1
    fimenquanto
Fimalgoritmo

